// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class KeyAction {
    "type": string;
    "shortcut"?: string;
    "command"?: string;
    "arguments"?: string;
    "workingDirectory"?: string;
    "application"?: string;
    "mediaControl"?: string;

    /** Creates a new KeyAction instance. */
    constructor($$source: Partial<KeyAction> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyAction instance from a string or object.
     */
    static createFrom($$source: any = {}): KeyAction {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyAction($$parsedSource as Partial<KeyAction>);
    }
}

export class KeyAssignment {
    "id": string;
    "label": string;
    "color": string;
    "brightness"?: number | null;
    "action": KeyAction;

    /** Creates a new KeyAssignment instance. */
    constructor($$source: Partial<KeyAssignment> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = (new KeyAction());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyAssignment instance from a string or object.
     */
    static createFrom($$source: any = {}): KeyAssignment {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("action" in $$parsedSource) {
            $$parsedSource["action"] = $$createField4_0($$parsedSource["action"]);
        }
        return new KeyAssignment($$parsedSource as Partial<KeyAssignment>);
    }
}

// Private type creation functions
const $$createType0 = KeyAction.createFrom;
