// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

export function ApplyKeyAction(index: number, action: config$0.KeyAction): $CancellablePromise<app$0.DashboardState> {
    return $Call.ByID(1905372150, index, action).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ApplyKeySettings(index: number, action: config$0.KeyAction, color: string, brightness: number): $CancellablePromise<app$0.DashboardState> {
    return $Call.ByID(226223513, index, action, color, brightness).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ClearKeyAction(index: number): $CancellablePromise<app$0.DashboardState> {
    return $Call.ByID(1702418321, index).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetDashboardState(): $CancellablePromise<app$0.DashboardState> {
    return $Call.ByID(4213142764).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveToDevice(): $CancellablePromise<app$0.DashboardState> {
    return $Call.ByID(3963280321).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = app$0.DashboardState.createFrom;
