// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "./internal/app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";

export function ApplyKeyAction(index: number, action: config$0.KeyAction): $CancellablePromise<app$0.DashboardState> {
    return $Call.ByID(864729253, index, action).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ClearKeyAction(index: number): $CancellablePromise<app$0.DashboardState> {
    return $Call.ByID(17620114, index).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetDashboardState(): $CancellablePromise<app$0.DashboardState> {
    return $Call.ByID(1070296609).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveToDevice(): $CancellablePromise<app$0.DashboardState> {
    return $Call.ByID(437581394).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = app$0.DashboardState.createFrom;
