// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

export class BatteryStatus {
    "state": string;
    "label": string;
    "detail": string;
    "batteryMV": number;
    "charging": boolean;

    /** Creates a new BatteryStatus instance. */
    constructor($$source: Partial<BatteryStatus> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("batteryMV" in $$source)) {
            this["batteryMV"] = 0;
        }
        if (!("charging" in $$source)) {
            this["charging"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatteryStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): BatteryStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatteryStatus($$parsedSource as Partial<BatteryStatus>);
    }
}

export class DashboardState {
    "profile": string;
    "dongleStatus": DeviceConnectionStatus;
    "macropadStatus": DeviceConnectionStatus;
    "batteryStatus": BatteryStatus;
    "keyAssignments": config$0.KeyAssignment[];
    "dirty": boolean;
    "saved": boolean;

    /** Creates a new DashboardState instance. */
    constructor($$source: Partial<DashboardState> = {}) {
        if (!("profile" in $$source)) {
            this["profile"] = "";
        }
        if (!("dongleStatus" in $$source)) {
            this["dongleStatus"] = (new DeviceConnectionStatus());
        }
        if (!("macropadStatus" in $$source)) {
            this["macropadStatus"] = (new DeviceConnectionStatus());
        }
        if (!("batteryStatus" in $$source)) {
            this["batteryStatus"] = (new BatteryStatus());
        }
        if (!("keyAssignments" in $$source)) {
            this["keyAssignments"] = [];
        }
        if (!("dirty" in $$source)) {
            this["dirty"] = false;
        }
        if (!("saved" in $$source)) {
            this["saved"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DashboardState instance from a string or object.
     */
    static createFrom($$source: any = {}): DashboardState {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dongleStatus" in $$parsedSource) {
            $$parsedSource["dongleStatus"] = $$createField1_0($$parsedSource["dongleStatus"]);
        }
        if ("macropadStatus" in $$parsedSource) {
            $$parsedSource["macropadStatus"] = $$createField2_0($$parsedSource["macropadStatus"]);
        }
        if ("batteryStatus" in $$parsedSource) {
            $$parsedSource["batteryStatus"] = $$createField3_0($$parsedSource["batteryStatus"]);
        }
        if ("keyAssignments" in $$parsedSource) {
            $$parsedSource["keyAssignments"] = $$createField4_0($$parsedSource["keyAssignments"]);
        }
        return new DashboardState($$parsedSource as Partial<DashboardState>);
    }
}

export class DeviceConnectionStatus {
    "state": string;
    "label": string;
    "detail": string;
    "path"?: string;

    /** Creates a new DeviceConnectionStatus instance. */
    constructor($$source: Partial<DeviceConnectionStatus> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceConnectionStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceConnectionStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceConnectionStatus($$parsedSource as Partial<DeviceConnectionStatus>);
    }
}

// Private type creation functions
const $$createType0 = DeviceConnectionStatus.createFrom;
const $$createType1 = BatteryStatus.createFrom;
const $$createType2 = config$0.KeyAssignment.createFrom;
const $$createType3 = $Create.Array($$createType2);
